### ISSUE TITLE
Design files

### ISSUE THREAD

**Issue by emaker** [raspberrypilearning/3d-printed-astro-pi-flight-case#3]
This is an awesome project, and a great way to get people involved with science.

The APEM buttons are indeed expensive, but also a non standard size. Panel mount buttons to fit an 8mm hole in the panel are much cheaper and more common.

Could you share the design files so I can modify the hole sizes to suit, and then share this with the community?

**Comment by davidhoness** [comment]
Thanks! So the CAD files are only available in STL format [here](https://github.com/raspberrypilearning/3d-printed-astro-pi-flight-case/tree/master/STL).
See the FAQ on our original [blog post](https://www.raspberrypi.org/blog/astro-pi-3d-print-your-own-flight-case/) for more information.
